/** 路由 → 所需权限码（单一事实源，菜单与路由守卫共用）。 */
export const ROUTE_PERMS: Record<string, string> = {
  '/dashboard': '',
  '/account': '',
  '/chat': 'chat:use',
  '/kb': 'kb:read',
  '/retrieval': 'retrieval:query',
  '/todo': 'chat:use',
  '/approvals': 'workflow:read',
  '/eval': 'eval:read',
  '/agents': 'agent:read',
  '/skills': 'skill:read',
  '/scheduled': 'schedule:read',
  '/channels': 'channel:read',
  '/admin/channel-users': 'channel:read',
  '/admin/tools': 'tool:read',
  '/admin/mcp': 'mcp:read',
  '/admin/settings': 'system:manage',
  '/admin/system-ops': 'system:manage',
  '/admin/notify-channels': 'notify:read',
  '/admin/event-subscriptions': 'notify:read',
  '/admin/email-sources': 'kb:read',
  '/service-tickets': 'service:read',
  '/records': 'record:read',
  '/admin/models': 'model:read',
  '/admin/users': 'user:read',
  '/admin/roles': 'role:read',
  '/admin/depts': 'dept:read',
  '/admin/groups': 'group:read',
  '/admin/audit': 'audit:read',
  '/admin/logs': 'system:read',
  '/admin/api-keys': 'apikey:read',
  '/admin/sso': 'sso:read',
  '/admin/usage': 'model:read',
  '/admin/security': 'audit:read',
  '/admin/files': 'file:manage',
}
